# Numpy

In [2]:
import numpy as np

a1 = np.array([1,2,3,4])
print(type(a1))

<class 'numpy.ndarray'>


In [4]:
# dtype
print(np.array([1,2,3,4], dtype = float))
print(np.array([1,2,3,4], dtype = bool))

[1. 2. 3. 4.]
[ True  True  True  True]


In [10]:
# np.arange
np.arange(12,dtype=int).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
# np.random.random
np.random.random((3,2))

array([[0.3876307 , 0.72111445],
       [0.33094859, 0.04556789],
       [0.88238888, 0.46395375]])

In [94]:
# np.linspace
a2 = np.linspace(1,20,10,dtype=np.float16).reshape(2,5)
a2

array([[ 1.   ,  3.111,  5.223,  7.332,  9.445],
       [11.555, 13.664, 15.78 , 17.89 , 20.   ]], dtype=float16)

In [68]:
a2.ndim

2

In [121]:
# astype
a2.astype(np.int64)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 20]])

## Array Operations

In [119]:
# Scalar Operation ( Arithmetic Operations )
np.array(a2 * 1, dtype=int)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 20]])

In [120]:
# Relational Operations
a2 > 2

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Vector Operations

In [150]:
# Arithmetic Operations
a1 = np.random.randint(1,21,size=(4,5))
a1

array([[12,  1,  1,  8,  2],
       [ 4, 15,  5,  3,  9],
       [ 3, 11,  2, 14, 13],
       [ 7,  9, 12,  6, 10]])

In [151]:
# Arithmetic Operations
a2 = np.random.randint(20,41,size=(4,5))
a2

array([[35, 31, 20, 40, 36],
       [28, 23, 40, 37, 38],
       [32, 31, 29, 38, 31],
       [38, 31, 38, 32, 36]])

In [158]:
np.round(a1*10)

array([[120,  10,  10,  80,  20],
       [ 40, 150,  50,  30,  90],
       [ 30, 110,  20, 140, 130],
       [ 70,  90, 120,  60, 100]])

In [21]:
a1 = np.arange(12,dtype=int).reshape(3,2,2)
a1.astype(np.int64)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [182]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(4,2)
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [183]:
a2

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [184]:
np.dot(a1,a2)

array([[ 76,  82],
       [252, 274]])

In [64]:
np.diag(a1)

array([0, 4, 8])

In [72]:
# Corner Elements

a1[::2,::2]

array([[0, 2],
       [6, 8]])

# Advance Numpy

### - Numpy Array Vs Python list

In [76]:
# Speed of Python List

a = [ i for i in range(10000000)]
b = [ i for i in range(10000000,20000000)]

c = []

# import time lib
import time as t

start = t.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(t.time()-start)

0.8338868618011475


In [79]:
# Speed of Numpy Array

# import numpy and time lib
import numpy as np
import time as t

a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = t.time()
c = a + b
print(t.time()-start)

0.029526710510253906


In [89]:
np.random.randint(1,20,24)

array([18, 10, 13, 12, 12,  1,  6,  2, 15,  9, 12, 16, 14, 12, 10,  6, 16,
       11, 18, 19, 12, 19, 11,  5])

In [92]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
print(a[1:3,1:])

[[4 5]
 [7 8]]


## Fancy Indexing

In [124]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [127]:
# Assigning random index and printing

print(a[[1,2,3],[1,2,0]])

[ 5 10 12]


## Booleab Indexing

In [152]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[17, 31, 41,  1],
       [57, 50, 80, 20],
       [63, 33, 95, 25],
       [68, 66, 66, 35],
       [50, 35, 62, 23],
       [41, 57, 57, 40]])

In [168]:
# Printing no that are greater that 50
a[(a > 50) & (a % 2 == 0)]

array([80, 68, 66, 66, 62])

## Diff between "&" and "and"
`"&"` - is a bit wise Operator  
`"and"` - is a logical Operator

# Broadcasting

### **1. Make the two arrays have the same number of dimensions**
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

### **2. Make each dimension of the two arrays the same size.**
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.
<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [213]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [214]:
b = np.arange(3).reshape(3)
b

array([0, 1, 2])

# Working with Mathematical Formulas by creating your own functions
### 1. Sigmoid

In [216]:
# Sigmoid
def sigmoid(array):
    return 1/(1 + np.exp(array))

In [218]:
a = np.arange(10)
print(sigmoid(a))

[5.00000000e-01 2.68941421e-01 1.19202922e-01 4.74258732e-02
 1.79862100e-02 6.69285092e-03 2.47262316e-03 9.11051194e-04
 3.35350130e-04 1.23394576e-04]
